# Inputs
input {
    kb_layout = pl
    numlock_by_default = true
    follow_mouse = 1
    sensitivity = 0.5
    accel_profile = adaptive

    touchpad {
        natural_scroll = false
        tap-to-click = true
    }
}

gestures {
    workspace_swipe_touch = true
    workspace_swipe_cancel_ratio = 0.1
}

# New Gestures System
gesture = 3, horizontal, workspace

# Custom gestures
gesture = 4, left, dispatcher, changegroupactive, b
gesture = 4, right, dispatcher, changegroupactive, f
gesture = 3, up, dispatcher, exec, $launcher
gesture = 3, down, dispatcher, exec, $launcher
