# Appearance (Battery Optimized + Waybar Aligned)
general {
    gaps_in = 3
    gaps_out = 5
    border_size = 2
    col.active_border = rgba(cba6f7ff) # Mauve (Waybar Active)
    col.inactive_border = rgba(313244ff) # Surface0 (Waybar Inactive)
    layout = dwindle
}

decoration {
    rounding = 0
    shadow {
        enabled = false
    }
    blur {
        enabled = false # Disabled for energy efficiency
    }
}

group {
    col.border_active = rgba(cba6f7ff)
    col.border_inactive = rgba(313244ff)

    groupbar {
        enabled = true
        font_family = AtkynsonMono Nerd Font
        font_size = 12
        font_weight_active = bold
        font_weight_inactive = bold
        text_color = rgba(cdd6f4ff) # Text color
        col.active = rgba(cba6f7ff) # Mauve
        col.inactive = rgba(313244ff) # Surface0
        height = 20
    }
}

animations {
    enabled = true
    
    bezier = simple, 0.16, 1, 0.3, 1
    
    animation = windows, 1, 2, simple, slide
    animation = windowsOut, 1, 2, simple, slide
    animation = fade, 1, 2, simple
    animation = workspaces, 1, 3, simple, slide
    animation = specialWorkspace, 1, 3, simple, slidevert
}

dwindle {
    pseudotile = true
    preserve_split = true
}
