# Workspace Rules
workspace = 10, defaultName:term

# Window Rules
windowrule = float on, match:title (^WPRS.*$)
windowrule = float on, match:title (^nmtui$)
windowrule = float on, match:class (^org.pulseaudio.pavucontrol$)
windowrule = float on, match:class (^nm-connection-editor$)
windowrule = float on, match:class (^blueman-manager$)
windowrule = float on, match:class (^xdg-desktop-portal-gtk$)
windowrule = float on, pin on, match:title (^Picture in picture$)
windowrule = float on, match:class (^google-chrome-beta-glic$)

