# Workspace Rules
workspace = 10, defaultName:term

# Window Rules
# hyprlang noerror true
# Old syntax (< v0.53.0)
windowrulev2 = float, title:(^WPRS.*$)
windowrulev2 = float, title:(^nmtui$)
windowrulev2 = float, class:(^org.pulseaudio.pavucontrol$)
windowrulev2 = float, class:(^nm-connection-editor$)
windowrulev2 = float, class:(^blueman-manager$)
windowrulev2 = float, class:(^xdg-desktop-portal-gtk$)
windowrulev2 = float, title:(^Picture in picture$)
windowrulev2 = pin, title:(^Picture in picture$)
windowrulev2 = float, class:(^google-chrome-beta-glic$)

# New syntax (>= v0.53.0)
windowrule = float on, match:title (^WPRS.*$)
windowrule = float on, match:title (^nmtui$)
windowrule = float on, match:class (^org.pulseaudio.pavucontrol$)
windowrule = float on, match:class (^nm-connection-editor$)
windowrule = float on, match:class (^blueman-manager$)
windowrule = float on, match:class (^xdg-desktop-portal-gtk$)
windowrule = float on, pin on, match:title (^Picture in picture$)
windowrule = float on, match:class (^google-chrome-beta-glic$)
# hyprlang noerror false

