# Misc (Battery Optimized)
misc {
    disable_hyprland_logo = true
    force_default_wallpaper = 0
    disable_splash_rendering = true
    # vfr = true
    vrr = 1
    # render_unfocused_fps = 10 # Reduce power for background windows
    background_color = 0x000000 # Solid black for OLED/energy saving
}
