# Open any image in the full kitty window by clicking on it
protocol file
mime image/*
action launch --type=window kitten icat --hold -- ${FILE_PATH}

# Open directories
protocol file
mime inode/directory
action launch --type=window --cwd -- $FILE_PATH

# Open things in Chrome
protocol file
mime audio/*
action launch --type=background xdg-open ${FILE_PATH}

protocol file
mime video/*
action launch --type=background xdg-open ${FILE_PATH}

protocol file
mime application/*
action launch --type=background xdg-open ${FILE_PATH}

# Open files in Vim
protocol file
action launch --type=window nvim ${FILE_PATH}
