# --- Variables ---
# Set the modifier key (Super/Windows key)
set $mod Mod4
set $term kitty
# zsh -i in order to have the potential envs
set $launcher zsh -i -c "pkill rofi || rofi -show combi"

font AtkynsonMono Nerd Font Bold 10
