# --- Startup Programs ---
# exec_always ensures these restart if they crash
# exec runs only once on startup
exec dbus-update-activation-environment --systemd XDG_CURRENT_DESKTOP=sway XDG_SESSION_TYPE=wayland
# Alternative/complementary for systemd units
exec systemctl --user import-environment XDG_CURRENT_DESKTOP XDG_SESSION_TYPE WAYLAND_DISPLAY DISPLAY
exec nm-applet --indicator
exec blueman-applet
exec playerctld daemon
# exec_always pgrep 'waybar' || waybar
exec_always pgrep 'swayidle' || swayidle -w
exec_always pgrep 'swtchrd' || swtchrd
exec_always pkill kanshi; sleep 3 && kanshi >~/.tmp/kanshi.stdout 2>~/.tmp/kanshi.stderr
exec_always swaync
exec_always swayosd-server

bar {
    swaybar_command waybar
    position top
    # mode hide
    # modifier Mod4
}

