# --- Input Configuration ---
# Use 'swaymsg -t get_inputs' to find specific device identifiers if needed.
input * {
    xkb_layout pl
    xkb_numlock enable
    pointer_accel 0.5
}

input type:touchpad {
    natural_scroll disabled
    tap enabled
    accel_profile "adaptive"
    pointer_accel 0.5
}

input "type:keyboard" {
    # xkb_options caps:swapescape
}
