# --- General Appearance & Layout ---
# Gaps
gaps inner 3
gaps outer 5

# Borders
default_border none
# Colors definition:      border      background  text        indicator   child_border
client.focused            #89b4fa     #1e1e2eda   #cdd6f4     #89b4fa     #00000000
client.unfocused          #7f849c     #1e1e2eda   #cdd6f4     #7f849c     #00000000
client.focused_inactive   #7f849c     #1e1e2eda   #cdd6f4     #7f849c     #00000000
client.urgent             #f38ba8     #1e1e2eda   #cdd6f4     #f38ba8     #00000000
client.placeholder        #7f849c     #1e1e2eda   #cdd6f4     #7f849c     #00000000


focus_follows_mouse yes
