# --- Window Rules ---
for_window [title="^WPRS.*"] floating enable
for_window [title="nmtui"] floating enable
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable
for_window [app_id="nm-connection-editor"] floating enable
for_window [app_id="blueman-manager"] floating enable
for_window [window_type="dialog"] floating enable
for_window [window_role="dialog"] floating enable
for_window [app_id = "xdg-desktop-portal-gtk"] floating enable;
for_window [title = "Picture in picture"] floating enable;
for_window [title = "Picture in picture"] sticky enable;
focus_on_window_activation focus
