hl.window_rule({ match = { title = "^WPRS.*$" }, float = true })
hl.window_rule({ match = { title = "^nmtui$" }, float = true })
hl.window_rule({ match = { class = "^org.pulseaudio.pavucontrol$" }, float = true })
hl.window_rule({ match = { class = "^nm-connection-editor$" }, float = true })
hl.window_rule({ match = { class = "^blueman-manager$" }, float = true })
hl.window_rule({ match = { class = "^xdg-desktop-portal-gtk$" }, float = true })
hl.window_rule({ match = { title = "^Picture in picture$" }, float = true, pin = true })
hl.window_rule({ match = { class = "^google-chrome-beta-glic$" }, float = true })
