# Hyprland Config
# Sources
source = ~/.config/hypr/config.d/00-variables.conf
source = ~/.config/hypr/config.d/01-autostart.conf
source = ~/.config/hypr/config.d/02-inputs.conf
source = ~/.config/hypr/config.d/03-appearance.conf
source = ~/.config/hypr/config.d/04-outputs.conf
source = ~/.config/hypr/config.d/05-window-rules.conf
source = ~/.config/hypr/config.d/09-misc.conf
source = ~/.config/hypr/config.d/10-keybindings.conf

# Nogit (Machine/User specific)
source = ~/.config/hypr/config.d/*.nogit.conf
