-- Hyprland Lua Configuration (0.55+)

-- Modular imports
require("lua/00-variables")
require("lua/01-autostart")
require("lua/02-inputs")
require("lua/03-appearance")
require("lua/04-outputs")
require("lua/05-window-rules")
require("lua/09-misc")
require("lua/10-keybindings")

-- Machine-specific configurations (dynamic sourcing of _nogit.lua files)
local home = os.getenv("HOME")
local config_dir = home .. "/.config/hypr"
local handle = io.popen('ls ' .. config_dir .. '/lua/*_nogit.lua 2>/dev/null')
if handle then
    for file in handle:lines() do
        -- Extract the module name (e.g., lua/04-outputs_nogit)
        local module = file:match(".*/(lua/.-)%.lua$")
        if module then
            pcall(require, module)
        end
    end
    handle:close()
end

-- Final configuration settings
hl.config({
    autogenerated = false
})
