set -g @catppuccin_flavor 'mocha'

set -g @catppuccin_window_status_style "basic"
set -g @catppuccin_window_text_color "#{@thm_crust}"
set -g @catppuccin_window_current_text_color "#{@thm_surface_0}"

set -g @catppuccin_window_text " #[fg=#{@thm_overlay_1}]#{s|([^/]+)$|#[fg=#{@thm_fg}]\\1|:#{s|([^/])[^/]*/|\\1/|:#{s|([^/])[^/]*/|\\1/|:pane_current_path}}} ❯ #W#{?#{==:#{s/ +$//:pane_title},#{host}},, ❯ #{s/ +$//:pane_title}}"
set -g @catppuccin_window_current_text " #[fg=#{@thm_overlay_1}]#{s|([^/]+)$|#[fg=#{@thm_fg}]\\1|:#{s|([^/])[^/]*/|\\1/|:#{s|([^/])[^/]*/|\\1/|:pane_current_path}}} ❯ #W#{?#{==:#{s/ +$//:pane_title},#{host}},, ❯ #{s/ +$//:pane_title}}"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Make the status line more pleasant.
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_session}#{E:@catppuccin_status_date_time}"

# Ensure that everything on the status line
# is included.
set -g status-left-length 100
set -g status-right-length 100

unbind C-b
set-option -g prefix C-x
bind-key C-x send-prefix

bind = split-window -h
bind - split-window -v
unbind '"'
unbind %

bind r source-file ~/.tmux.conf

# Split panes with a specific size
bind -n M-= split-window -v -p 20

# start numeration from 1 to align with the keyboard
set -g base-index 1

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Switch panes using Alt-shift-<vim motions>
bind -n M-H select-pane -L
bind -n M-L select-pane -R
bind -n M-K select-pane -U
bind -n M-J select-pane -D

# Switch windows (tabs) using Alt-Shift-Arrow without prefix
bind-key -n M-S-Left previous-window
bind-key -n M-S-Right next-window

# switch windows (tabs) using Alt+number without prefix
bind-key -n M-0 select-window -t 0
bind-key -n M-1 select-window -t 1
bind-key -n M-2 select-window -t 2
bind-key -n M-3 select-window -t 3
bind-key -n M-4 select-window -t 4
bind-key -n M-5 select-window -t 5
bind-key -n M-6 select-window -t 6
bind-key -n M-7 select-window -t 7
bind-key -n M-8 select-window -t 8
bind-key -n M-9 select-window -t 9

# Resize panes using Ctrl-Alt-<vim keys> without prefix
bind-key -n C-M-k resize-pane -U 5
bind-key -n C-M-j resize-pane -D 5
bind-key -n C-M-h resize-pane -L 5
bind-key -n C-M-l resize-pane -R 5

set -g mouse on
set -g set-clipboard on
set -as terminal-features ',rxvt-unicode-256color:clipboard'
set -sg terminal-overrides ",*:RGB"
setw -g allow-passthrough on

